config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :films do
  end
  resources :actors do
    member do
      get '/new_film', to: 'actors#newfilm'
      post '/new_film', to: 'actors#createfilm'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Actor < ApplicationRecord
    has_and_belongs_to_many :films
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Film < ApplicationRecord
    has_and_belongs_to_many :actors
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    def index
        @actors = Actor.all
    end

    def show
        @actor = Actor.find(params[:id])
    end

    def new
        @actor = Actor.new
    end

    def create
        name = params[:actor][:name]
        Actor.create({name: name})
        redirect_to actors_path
    end

    def newfilm
        @actor = Actor.find(params[:id])
        @film = Film.new
    end

    def createfilm
        name = params[:film][:name]
        f = Film.create({name: name})
        a = Actor.find(params[:id])
        a.films.push(f)
        redirect_to actor_path(a)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
    def new 
        @film = Film.new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<h1> Actors </h1>

<ul>
<% @actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %></li>
<% end %>
</ul>

<%= link_to "New Actor", new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= form_with(model: @actor, local: true) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

app/views/actors/newfilm.html.erb
<h1>New Film</h1>

<%= form_with(url: new_film_actor_path(@actor), model: @film, local: true) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

app/views/actors/show.html.erb
<h1>Actor - <%= @actor.name %> Detail</h1>

<ul>
    <li>ID: <%= @actor.id %></li>
    <li>NAME: <%= @actor.name %></li>
</ul>

<h2>Films</h2>
<ul>
<% @actor.films.each do |film| %>
    <li><%= film.name %></li>
<% end %>
    
<%= link_to "Add Films", new_film_actor_path(@actor) %>

<%= link_to "All Actors", actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Films</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>